# Generated by Django 4.2 on 2024-05-14 00:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 13, 0, 40, 40, 391225, tzinfo=datetime.timezone.utc), verbose_name='Fecha Caducidad'),
        ),
    ]
